title: Rodrigo Patricio
author: Rodrigo Patricio
email: rpatriciocarvalho@gmail.com

description: Um blog sobre devaneios, desenvolvimento de software, ciência de dados e outras coisas mais.

remote_theme: "jekyll/minima@c6e74bb"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: rpatriciocarvalho
instagram_username: rodrigopatricio.br
rss: rss

show_excerpts: false

header_pages:
  - index.md

google_analytics: G-8XVM6LV5YM

minima:
  date_format: "%d/%m/%Y"