title: Rodrigo Patricio
author:
  name: Rodrigo Patricio
  email: rpatriciocarvalho@gmail.com

description: Um blog sobre devaneios, desenvolvimento de software, ciência de dados e outras coisas mais.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  #nav_pages:
  #  - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%d/%m/%Y"

  social_links:
    - title: Github
      icon: github
      url: "https://github.com/rpatriciocarvalho"
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/rodrigopatricio.br"